data:
  skab_path: "./data/SKAB/"
  batadal_path: "./data/BATADAL/"
  
model_params:
  deep_learning:
    max_epochs: 50
    batch_size: 32
    patience: 5
  automata:
    window_size: 4
    alphabet_size: 3

experiment:
  random_seeds: [42, 123, 2026, 7, 999]
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2